name: always
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: make ci

    - name: Install Cross
      run: cargo install cross --git https://github.com/cross-rs/cross

    - name: Build all artifacts
      run: make build-all
